// <auto-generated />
using System;
using BarideWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BarideWeb.Migrations
{
    [DbContext(typeof(BarideDbContext))]
    [Migration("20260315201110_AddContact")]
    partial class AddContact
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BarideWeb.Models.AppParameter", b =>
                {
                    b.Property<Guid>("ParamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("ParamId");

                    b.HasIndex("TenantId");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            ParamId = new Guid("c0000000-0000-0000-0000-000000000001"),
                            Description = "طريقة عرض المراسلة: 0=في صفحة جديدة، 1=في نافذة منبثقة، 2=في نفس الصفحة",
                            Key = "CorrespViewMode",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Value = "0"
                        },
                        new
                        {
                            ParamId = new Guid("c0000000-0000-0000-0000-000000000010"),
                            Description = "الدقة الافتراضية للماسح الضوئي (DPI): 100, 150, 200, 300, 600",
                            Key = "ScannerDpi",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Value = "200"
                        },
                        new
                        {
                            ParamId = new Guid("c0000000-0000-0000-0000-000000000011"),
                            Description = "وضع اللون الافتراضي للماسح الضوئي: Color, Grayscale",
                            Key = "ScannerPixelMode",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Value = "Grayscale"
                        },
                        new
                        {
                            ParamId = new Guid("c0000000-0000-0000-0000-000000000012"),
                            Description = "صيغة الصورة الافتراضية للماسح الضوئي: JPG, PNG, PDF",
                            Key = "ScannerImageFormat",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Value = "PDF"
                        });
                });

            modelBuilder.Entity("BarideWeb.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BarideWeb.Models.Categorie", b =>
                {
                    b.Property<Guid>("CatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("CatId");

                    b.HasIndex("TenantId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Designation = "المراسلات",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Designation = "المحاضر",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Designation = "التقارير",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000004"),
                            Designation = "عروض الحال",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000005"),
                            Designation = "سندات الطلب",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000006"),
                            Designation = "الدعوات",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000007"),
                            Designation = "الاعلانات",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000008"),
                            Designation = "المذكرات",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-000000000009"),
                            Designation = "الشهادات",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-00000000000a"),
                            Designation = "المقررات",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            CatId = new Guid("a0000000-0000-0000-0000-00000000000b"),
                            Designation = "التهاني",
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("BarideWeb.Models.Contact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BarideWeb.Models.Corresp", b =>
                {
                    b.Property<Guid>("Cid")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CorrespRep")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateArrivDepart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateCorresp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Expediteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Num")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumInterne")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Objet")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Observation")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Cid");

                    b.HasIndex("CatId");

                    b.HasIndex("TenantId");

                    b.ToTable("Correspondances");
                });

            modelBuilder.Entity("BarideWeb.Models.Doc", b =>
                {
                    b.Property<Guid>("DocId")
                        .HasColumnType("uuid");

                    b.Property<string>("Chemin")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("Cid")
                        .HasColumnType("uuid");

                    b.Property<string>("Designation")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.HasKey("DocId");

                    b.HasIndex("Cid");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("BarideWeb.Models.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("b0000000-0000-0000-0000-000000000001"),
                            Name = "المؤسسة الرئيسية"
                        });
                });

            modelBuilder.Entity("BarideWeb.Models.Transfert", b =>
                {
                    b.Property<Guid>("TransfertId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Cid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTransfert")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("boolean");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("text");

                    b.Property<string>("SenderId")
                        .HasColumnType("text");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("TransfertId");

                    b.HasIndex("Cid");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.HasIndex("TenantId");

                    b.ToTable("Transferts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BarideWeb.Models.AppParameter", b =>
                {
                    b.HasOne("BarideWeb.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BarideWeb.Models.AppUser", b =>
                {
                    b.HasOne("BarideWeb.Models.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BarideWeb.Models.Categorie", b =>
                {
                    b.HasOne("BarideWeb.Models.Tenant", "Tenant")
                        .WithMany("Categories")
                        .HasForeignKey("TenantId");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BarideWeb.Models.Corresp", b =>
                {
                    b.HasOne("BarideWeb.Models.Categorie", "Categ")
                        .WithMany("Corresps")
                        .HasForeignKey("CatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarideWeb.Models.Tenant", "Tenant")
                        .WithMany("Correspondances")
                        .HasForeignKey("TenantId");

                    b.Navigation("Categ");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("BarideWeb.Models.Doc", b =>
                {
                    b.HasOne("BarideWeb.Models.Corresp", "Corresp")
                        .WithMany("Docs")
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corresp");
                });

            modelBuilder.Entity("BarideWeb.Models.Transfert", b =>
                {
                    b.HasOne("BarideWeb.Models.Corresp", "Corresp")
                        .WithMany()
                        .HasForeignKey("Cid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarideWeb.Models.AppUser", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId");

                    b.HasOne("BarideWeb.Models.AppUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId");

                    b.HasOne("BarideWeb.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId");

                    b.Navigation("Corresp");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BarideWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BarideWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BarideWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BarideWeb.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BarideWeb.Models.Categorie", b =>
                {
                    b.Navigation("Corresps");
                });

            modelBuilder.Entity("BarideWeb.Models.Corresp", b =>
                {
                    b.Navigation("Docs");
                });

            modelBuilder.Entity("BarideWeb.Models.Tenant", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Correspondances");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
